<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Dreamine.Gem300.csproj" />
    <ProjectReference Include="..\..\..\Gem\Dreamine.Gem.csproj" />
  </ItemGroup>
</Project>
