<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup Condition="'$(UseLocalDreamineSources)' == 'true'">
    <ProjectReference Include="..\..\Dreamine.Gem300.csproj" />
    <ProjectReference Include="..\..\..\Gem\Dreamine.Gem.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalDreamineSources)' != 'true'">
    <PackageReference Include="Dreamine.Gem300" />
  </ItemGroup>
</Project>
